global:
  scrape_interval: 5s  #Every 5 seconds, ask the gateway for metrics.

scrape_configs:
  - job_name: "gateway"

    static_configs:
      - targets:
          - gateway:8000  #Which application should I monitor?
 